### ISSUE TITLE
0.12.0. Compatibility with FireMonkey

### ISSUE THREAD

**Issue by eberhardweber** [PotcFdk/SteamDiscoveryQueueAutoSkipper#11]
Previous to version 0.12.0., this script also worked with [FireMonkey](https://addons.mozilla.org/en-GB/firefox/addon/firemonkey/). As of 0.12.0., however, changes to the script have unfortunately made it stop working on it. 

FireMonkey's author suggested adding either

`@inject-into     page`
or 
`@run-at     document-end`

to the script via FireMonkey's [User Metadata](https://erosman.github.io/support/content/help.html#User-Metadata) function, but so far I've had no luck running the script with either addition.

Since the script did work with FireMonkey on version 0.11.1, it might not be a huge change to make it compatible again.

**Comment by Mx772** [comment]
Just a heads up to anyone that reads this; it's an easy fix. 
The issue as mentioned by erosman in the above is due to
```
SyntaxError: return not in function
```
on lines 47 & 147 ->

On FireMonkey, click on the script > edit > 'Wrap code in IIFE' 
![image](https://github.com/PotcFdk/SteamDiscoveryQueueAutoSkipper/assets/9059161/04236574-16fd-47b8-bd50-1d8db4ebe6bd)
Then save it.

**Comment by PotcFdk** [comment]
This should be fixed with v1.0.0.
I can't test this right now but if you still have issues please let me know.
